# Generated by Django 5.2.1 on 2025-05-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_finalizar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='finalizar',
            new_name='is_finalizada',
        ),
    ]
