# Generated by Django 5.2.1 on 2025-05-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_rename_finalizar_tarefa_is_finalizada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='media',
            new_name='prioridade',
        ),
    ]
